name: muze
description: Jam tunes with your friends!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^2.3.2+1
  fab_circular_menu: ^1.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flutter_screenutil: ^3.1.1
  google_sign_in: ^4.5.4
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  page_transition: ^1.1.6
  path_provider: ^1.6.18
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ^1.10.3
  effective_dart: ^1.2.4
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  hive_generator: ^0.7.2+1
  pedantic: ^1.9.2

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-android.png'
  adaptive_icon_background: '#fafafa'
  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter_native_splash:
  image: assets/branding/logo.png
  color: "fafafa"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  assets:
     - assets/branding/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
